### ISSUE TITLE
Running with a Jetson Nano and USB Accelerator

### ISSUE THREAD

**Issue by parthjdoshi** [google-coral/example-object-tracker#1]
Hello. Thank you for the great example. I have a few questions regarding object trackers running on the Coral Accelerator attached to a Jetson Nano.
1) What is the speed of the tracker? I followed [this](https://github.com/nathanrooy/rpi-urban-mobility-tracker) repository for a DeepSORT tracker combined with MobileNet SSD, but the speeds were barely close to 2 FPS.
2) I am sorry if this is a dumb question, but how do you modify the Gstreamer code to read from and save output to a video file?
3) I have been trying to create a YOLOv4 + DeepSORT object tracker. Do you think that will provide realtime speeds on the Coral USB accelerator, or is the MobileNet version better, since it seems to be better supported by Coral?

Thank you for your help.

**Comment by manoj7410** [comment]
1. On an x86-64 machine with USB Accelerator connected over USB2.0 I get ~17-18 FPS with SORT Tracker. 

2. You can start to walk through the code at https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L205 and also explore the gstreamer pipeline at https://www.systutorials.com/docs/linux/man/1-gst-launch-1.0/ and https://gstreamer.freedesktop.org/documentation/coreelements/filesrc.html?gi-language=c

3. DeepSort Tracker is supposed to be faster than SORT but I haven't yet tested this configuration yet.

**Comment by arsenal-2004** [comment]
Hey @manoj7410 Thanks for the reply. I'll go through your suggestions on Gstreamer and see if I can get it to work
