### ISSUE TITLE
install_requirements.sh errors out: fatal error: Python.h

### ISSUE THREAD

**Issue by jlpoolen** [google-coral/example-object-tracker#16]
### Description

New install of Coral and this project.  Ran `bash gstreamer/install_requirements.sh` and script errored out with:

     aarch64-linux-gnu-g++: lap/lapmod.cpp
       lap/_lapjv.cpp:4:10: fatal error: Python.h: No such file or directory
        #include "Python.h"
                 ^~~~~~~~~~
       compilation terminated.

_Source: line 184 et seq.  from gstreamer_install_attemp_1.script.txt (uploaded)._

I then performed:

     sudo apt install python3-dev

then reran `bash install_requirements.sh` which then succeeded; see log at gstreamer_install_attempt_2.script.txt
[gstreamer_install_attemp_1.script.txt](https://github.com/google-coral/example-object-tracker/files/8498751/gstreamer_install_attemp_1.script.txt)
[gstreamer_install_attempt_2.script.txt](https://github.com/google-coral/example-object-tracker/files/8498752/gstreamer_install_attempt_2.script.txt)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

```shell
aarch64-linux-gnu-g++: lap/lapmod.cpp
    lap/_lapjv.cpp:4:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
```
</details>

**Comment by hjonnala** [comment]
Hi  @jlpoolen Thanks for reporting!  I have updated the install_requestments.sh file.
