### ISSUE TITLE
No install script for tracker

### ISSUE THREAD

**Issue by MxFxM** [google-coral/example-object-tracker#22]
### Description

The tracking software is a third party module.
In the README it is stated that the module will be downloaded when running install requirements.
However, there is no such installation script.
The only script is for downloading the models.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Documentation Bug

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
are you looking for the install_requirements.sh script in gstreamer folder: https://github.com/google-coral/example-object-tracker/tree/master/gstreamer ?
