### ISSUE TITLE
Pretty high system load on RPI 4

### ISSUE THREAD

**Issue by neilyoung** [google-coral/example-object-tracker#24]
### Description

Hi, I'm wondering what can make a system load of about 2.5-3 on an RPI. I mean, it is more or less some GStreamer stuff and USB 3 transfer, inference is running in the Coral TPU.

I'm using a USB camera as input (/dev/video1). PI is not overclocked, 2GB RAM

What could cause this high load, any ideas?

Other than that the inference is running fine. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Are you having the same system load for uncompiled tflite model? 

It could be due to the ML model running on EdgeTPU..Please check the power consumption section on page 5 for more details at: https://coral.ai/static/files/Coral-Accelerator-Module-datasheet.pdf

**Comment by neilyoung** [comment]
Could you please give me a hint, how I could make use of the uncompiled tflite model?

**Comment by neilyoung** [comment]
Strange. New day, new attempt. Now system load is 1.11, which would be ok

EDIT: But inference frame rate just 15 fps... Makes no sense

EDIT2: FPS seems to depend on content. I can also reach 30 fps with another view. Then the load is again at 2.5

**Comment by neilyoung** [comment]
While having you here may I ask you, if you are aware of any Coral based inference solution, which delivers 6DOF poses? I mean not only bounding boxes but also translation and rotation?

**Comment by hjonnala** [comment]
> Could you please give me a hint, how I could make use of the uncompiled tflite model?

Please download the ssd_mobilenet_v2_coco_quant_postprocess.tflite from [test_data](https://github.com/google-coral/test_data) repo to the models directory and update the model name at: https://github.com/google-coral/example-object-tracker/blob/master/gstreamer/detect.py#L147


> While having you here may I ask you, if you are aware of any Coral based inference solution, which delivers 6DOF poses? I mean not only bounding boxes but also translation and rotation?

I have responded to this one at: https://github.com/google-coral/project-posenet/issues/89.. Thanks!!

**Comment by neilyoung** [comment]
Thank you very much for both answers.

**Comment by neilyoung** [comment]
OK, system load is higher with uncompiled tflite model, between 2.5 and 3, while the original model is about 2. 6 fps inference rate.

**Comment by hjonnala** [comment]
> OK, system load is higher with uncompiled tflite model, between 2.5 and 3, while the original model is about 2. 6 fps inference rate.

Then the high system load is not due to ML model running on TPU. Please try the CPU usage monitoring tools to analyze what is causing this system load: https://linuxhint.com/raspberry-pi-cpu-usage-monitoring/ and check with rpi forum for any additional questions at: https://forums.raspberrypi.com/viewtopic.php?t=283330.. Thanks!

**Comment by neilyoung** [comment]
May I ask one last additional question? It is about the ID. I'm aware of the fact, that it can't really be a unique ID since it is detection, not recognition: Once you leave the FOV and return you'll get another ID. But is my assumption correct, that the ID is something not coming from the inference results (like bounding boxes), but is something "post-processed"?

**Comment by hjonnala** [comment]
The [ID](https://github.com/google-coral/example-object-tracker/blob/master/gstreamer/detect.py#L130) is coming from inference results and it would be mapped to bounding boxes.

**Comment by neilyoung** [comment]
Oh? Could you please point me to where the ID is derived? I was using the model with an older Coral application. I'm a bit lost where to find the ID.

This is how I'm deriving the bounding boxes, classes and scores:

```python
            boxes = self.interpreter.get_tensor(self.output_details[0]["index"])[0]
            classes = self.interpreter.get_tensor(self.output_details[1]["index"])[0]
            scores = self.interpreter.get_tensor(self.output_details[2]["index"])[0]

            for i in range(len(scores)):
                if scores[i] >= self.threshold and scores[i] <= 1.0:
                    ymin = int(max(1, (boxes[i][0] * height)))
                    ymax = int(min(height, (boxes[i][2] * height)))
                    xmin = int(max(1, (boxes[i][1] * width)))
                    xmax = int(min(width, (boxes[i][3] * width)))
                    object_name = self.labels[int(classes[i])]
                ...

```

Where to find the ID?

**Comment by hjonnala** [comment]
> ```python
> object_name = self.labels[int(classes[i])]
> ```


The ID is coming from classes and it would be mapped to [labels](https://github.com/google-coral/pycoral/blob/master/pycoral/utils/dataset.py#L20) (for ex [ID 2](https://github.com/google-coral/test_data/blob/master/coco_labels.txt#L3) would be car).

**Comment by neilyoung** [comment]
OK, then I think we are misunderstanding each other. I have run this model and got myself tagged as "id 34215" or so. Left the view. Another person got another ID. 

I think you are referring to the ID given in the coco.labels file

<img width="218" alt="image" src="https://user-images.githubusercontent.com/731020/200014982-672006af-6428-41ad-b869-9f94687c6305.png">

But this is not what I'm after :)

**Comment by neilyoung** [comment]
I mean this ID

<img width="291" alt="image" src="https://user-images.githubusercontent.com/731020/200020796-7548e8ce-4c57-49ff-b883-45967513a3a3.png">

EDIT:

~~It basically comes from "trackID" out of `trdata`. I can't figure out, where this `trdata` finally comes from. A GStreamer~~ ~~userCallback...~~ ~~Hmmm.. ~~

https://github.com/google-coral/example-object-tracker/blob/df20497f328ee48578e766e817a41b1e4f18a376/gstreamer/detect.py#L201

~~What is this "motTracker"?~~

**Comment by neilyoung** [comment]
EDIT: 
~~That "tracker.update(detections)"  - is it a "Sort" function?~~

~~Does that "Sort" object finally provide the ID?~~

EDIT: Ok, yes. "update" is provided by "sort". https://github.com/abewley/sort/blob/master/sort.py

Still not clear, what makes that "trackID"...

**Comment by neilyoung** [comment]
OK, after having made a deep dive into the code I confirm my own statement. The trackID is not coming from the inference, like bbox and score. It is resulting from a post process "sort", which assigns that "unique" id as long as the object is in view.

**Comment by neilyoung** [comment]
Today I ran it on a 32 bit Raspbian Buster. Runs with system load around 1. And it achieves 30 fps. I need to double check this, but my above attempts have been made with Bullseye Lite 64 bit.
