### ISSUE TITLE
ModuleNotFoundError: No module named 'sort'

### ISSUE THREAD

**Issue by dkinneyBU** [google-coral/example-object-tracker#27]
### Description

Getting the following from a Raspberry pi 4B. Doesn't appear to be any such module called "sort".

~/google-coral/example-object-tracker/gstreamer $ python detect.py --tracker sort
Loading ../models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with ../models/coco_labels.txt labels.
Traceback (most recent call last):
  File "/home/Merida/google-coral/example-object-tracker/gstreamer/detect.py", line 218, in <module>
    main()
  File "/home/Merida/google-coral/example-object-tracker/gstreamer/detect.py", line 209, in main
    result = gstreamer.run_pipeline(user_callback,
  File "/home/Merida/google-coral/example-object-tracker/gstreamer/gstreamer.py", line 239, in run_pipeline
    objectOfTracker = ObjectTracker(trackerName)
  File "/home/Merida/google-coral/example-object-tracker/gstreamer/tracker.py", line 32, in __init__
    self.trackerObject = SortTracker()
  File "/home/Merida/google-coral/example-object-tracker/gstreamer/tracker.py", line 41, in __init__
    from sort import Sort
ModuleNotFoundError: No module named 'sort'
Merida@Merida:~/google-coral/example-object-tracker/gstreamer $ pip install sort
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement sort
ERROR: No matching distribution found for sort

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by dkinneyBU** [comment]
Me again. detect.py works if I omit the --tracker argument. So, probably not a high priority issue. :-)

**Comment by hjonnala** [comment]
To install sort, Please try the steps mentioned at: https://github.com/google-coral/example-object-tracker/blob/master/gstreamer/install_requirements.sh#L56.. Thanks!

**Comment by hjonnala** [comment]
To install sort, Please try the steps mentioned at: https://github.com/google-coral/example-object-tracker/blob/master/gstreamer/install_requirements.sh#L56.. Thanks!
