### ISSUE TITLE
ModuleNotFoundError: No module named 'sort'

### ISSUE THREAD

**Issue by marcoruizrueda** [google-coral/example-object-tracker#3]
I have a "**No module named 'sort'**'" error when I run "`python3 detect.py --tracker sort`". I upgraded setuptools and sort, but It seems to be any other third party library. Any hint?
Thanks

**Comment by manoj7410** [comment]
On which host machine are you trying to run ? 
Did you run 'bash install_requirements.sh' ?

**Comment by marcoruizrueda** [comment]
I am trying on ubuntu20. 

Yes, I ran "sh install_requirements.sh" but there was an error there:
```
install_requirements.sh: 53: read: Illegal option -n
install_requirements.sh: 54: [[: not found
```
It worked after executing all the script steps by hand. Thanks for the response.
